name: sporran
version: 4.0.5
description: A PouchDB alike for Dart. Uses lawndart for local storage and Wilt for CouchDB access.
homepage: https://github.com/shamblett/sporran

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  wilt: '>=4.0.0 <=5.0.0'
  json_object_lite: '^2.1.0'

dev_dependencies:
  test: '^1.14.2'
  pana: '^0.13.5'
  pedantic: '^1.9.0'
  build_runner: '^1.8.0'
  build_test: '^0.10.12+1'
  build_web_compilers: '^2.8.0'

